### PR TITLE
Add covatars to participants page

### PR DESCRIPTION
**Pull request by KNGJOEL**
Added Covatars to community page of summer 2021 reading group
## Description

Added a community folder  under content/topics/reading_group
Added all covatars to the new community folder
Added each covatars with names to the community.en.md file

### CODE REVIEW

**Review by rebeccabilbro — CHANGES_REQUESTED** [review]
Thank you @KNGJOEL for adding the new images to our community page! I think it looks really nice and is a great way to memorialize the summer reading group experience. 

I have two requests:

- I noticed that you used the original images, each of which is about 12MB. Unfortunately these sizes will make our repository too large, which will slow down our development process and incur extra costs from Github. Please use an image compression method (which ever you prefer) to reduce the file sizes and update the files in this PR.
- Tianshu and Patrick were both part of the reading group, so their portraits need to be added.

**Comment by KNGJOEL** [comment]
> Thank you @KNGJOEL for adding the new images to our community page! I think it looks really nice and is a great way to memorialize the summer reading group experience.
> 
> I have two requests:
> 
> * I noticed that you used the original images, each of which is about 12MB. Unfortunately these sizes will make our repository too large, which will slow down our development process and incur extra costs from Github. Please use an image compression method (which ever you prefer) to reduce the file sizes and update the files in this PR.
> * Tianshu and Patrick were both part of the reading group, so their portraits need to be added.

Understood

**Comment by KNGJOEL** [comment]
Now Tianshu and Patrick are in. Also the overall size is 50.75 Mb. Every Covatar has decreased by at least 60% let me know if it is good for you.

**Review by rebeccabilbro — APPROVED** [review]
Thanks @KNGJOEL; reducing the file sizes of images is a good trick for avoiding Github thresholds (you may want to [read up on these a bit](https://stackoverflow.com/a/59479166/6552250) so that you know more about them in the future). 

Just to be on the safe side, I made the images a bit smaller, on the order of ~100KB; I also had to change them to JPG from PNG.  

I think we can go ahead and get this merged in now!

**Pull request merged**
